## In this exercise, we will use matrix factorization to fill the rating matrix
#### Let's Use this example of rating matrix (from the slides)

In [1]:

        
#         Item1  Item2  Item3
# User1     4      5      5
# User2     ?      5      5
# User3     ?      5      ?


In [1]:
import numpy as np

# identify the Known ratings based on the provided matrix: (user_index, item_index, rating_value)
ratings = [
    (0, 0, 4),
    (0, 1, 5),
    (0, 2, 5),
    (1, 1, 5),
    (1, 2, 5),
    (2, 1, 5),
]

In [2]:
# Main Parameters

num_users = 3
num_items = 3
k = 2                  # latent factors
lr = 0.01               # learning rate
epochs = 5000

### Step 1: Initialize latent space

* Each user → vector in ℝᵏ
* Each item → vector in ℝᵏ


scale = 0.1 → numbers are sampled with std deviation 0.1, Most numbers will be between roughly -0.3 and 0.3 (3σ rule)

size=(num_users, k) → create a (num_users × k) matrix

In [3]:
# Initialize embeddings, K is the dimension of each user and item vector
U = np.random.normal(scale=0.1, size=(num_users, k))
V = np.random.normal(scale=0.1, size=(num_items, k))

### Step 2: Learn from known ratings

* Compute prediction: U[u] @ V[i], @ is the matrix multiplication operator in python
* Compute error only on observed entries
* Update embeddings via gradient descent
    * err * V[i] → Move the user embedding toward the item embedding if the prediction is too low, or away if too high.
    * lr * (...) → Step size controls how fast we adjust

In [4]:
# Training with SGD (stocastic gradient decent)
for _ in range(epochs):
    for u, i, r in ratings:
        pred = np.clip(U[u] @ V[i], 0, 5) # keep the values between 0 and 5
        err = r - pred

        # Update rules: This rule adjusts the user embedding toward items they rated highly (and away from errors), 
        
        U[u] += lr * (err * V[i])  
        V[i] += lr * (err * U[u])

### Step 3: Predict missing values

* After training, U @ V.T gives all ratings
* Missing values are now filled with predictions

In [5]:
# Predicted full rating matrix
R_predicted = U @ V.T
R_clipped = np.clip(R_predicted, 0, 5) # keep the values between 0 and 5
print("Predicted ratings:")
print(np.round(R_clipped)) # round to integer


Predicted ratings:
[[4. 5. 5.]
 [3. 5. 5.]
 [3. 5. 4.]]


In [ ]:

        
#         Item1  Item2  Item3
# User1     4      5      5
# User2     ?      5      5
# User3     ?      5      ?
